#!/bin/sh
# Variables to change
chat="EDIT ME"
secret="EDIT ME"
msgaddress="http://localhost:5000/msg/"
# EO Variables to change


while [ 1 ]
do
    quote=`perl -e 'srand; rand($.) < 1 && ($line = $_) while <>; print $line;' quotes`
    msg="$quote"

    md5=`echo -n "$chat$msg$secret" | md5 -r`

    #md5sum prints a '-' to the end. Let's get rid of that.
    for m in $md5; do
        break
    done

    curl $msgaddress --data-urlencode chat="$chat" --data-urlencode msg="$msg" --data-urlencode md5="$m"
    echo -e "Sent: $quote"
    sleep 300
done
