#!/bin/sh
# Load config
source config.sh
# EO config


while [ 1 ]
do
    #time verification
    now=`date +"%H"`
    dayofweek=`date +"%u"`
    quote=`gshuf -n 1 quotes`
    msg="$quote"

    md5=`echo -n "$chat$msg$secret" | md5 -r`

    #md5sum prints a '-' to the end. Let's get rid of that.
    for m in $md5; do
        break
    done

    curl $msgaddress --data-urlencode chat="$chat" --data-urlencode msg="$msg" --data-urlencode md5="$m"
    echo -e "Sent: $quote"
    
if [ "$now" < "09" || "$now" > "18" ]
then
    sleep $(( $(date -j 0930 +%s) - $(date +%s) ))
elif [ "$dayofweek" > "5" ]
then
    sleep 1d
else
    sleep 300
fi
done
